services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - WHISPER_MODEL=small
      - GROQ_CHAT_MODEL=llama-3.1-8b-instant
      - GTTS_LANG=pt
      - GTTS_TLD=com.br
      - UVICORN_RELOAD=false
    restart: always
